# Generated by Django 2.2.3 on 2019-07-07 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcadaNome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Alcada',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('alcada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Alcada')),
            ],
            options={
                'verbose_name_plural': 'Usuario',
            },
        ),
    ]
