# Generated by Django 2.2.6 on 2019-10-28 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('anoTurma', models.IntegerField(primary_key=True, serialize=False)),
                ('ativo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='Crismando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dtNascimento', models.DateTimeField()),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('compl', models.CharField(blank=True, max_length=15, null=True)),
                ('nomeMae', models.CharField(max_length=100)),
                ('nomePai', models.CharField(max_length=100)),
                ('telMae', models.CharField(max_length=15)),
                ('telPai', models.CharField(max_length=15)),
                ('fezBatismo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('fezComunhao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crismando.Turma')),
            ],
            options={
                'verbose_name_plural': 'Crismando',
            },
        ),
    ]
