# Generated by Django 2.2.6 on 2019-10-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crismando', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crismando',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
