# Generated by Django 2.2.6 on 2019-10-28 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crismando', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtEncontro', models.DateField()),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Encontro',
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crismando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crismando.Crismando')),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encontro.Encontro')),
            ],
            options={
                'verbose_name_plural': 'Presenca',
            },
        ),
    ]
